### ISSUE TITLE
bhaptics OSC doesn't work with with face/eye tracking OSC

### ISSUE THREAD

**Issue by GingasVRFO** [HerpDerpinstine/bHapticsOSC#11]
could be something I'm doing.. i'm not sure.

But it seems like the eye tracking OSC doesn't work with the bhaptics one https://github.com/benaclejames/VRCFaceTracking

If I stop the eye tracking, bhaptics works fine, as soon as I'm running both, the eye tracking OSC seems to take priority and stops the bhaptics one from working

Tried changing Pipeallpackets in the ini if of Connection but that didn't help

**Comment by HerpDerpinstine** [comment]
Not an issue with bHapticsOSC.
You are only able to attach 1 thing to an OSC connection.
If you want to use multiple OSC applications at the same time you need an OSC Routing application to manage connection.
[VOR](https://github.com/SutekhVRC/VOR) by [SutekhVRC](https://github.com/SutekhVRC) is a popular one that I recommend you check out.
