### ISSUE TITLE
New Animation Controller breaks some animation layers

### ISSUE THREAD

**Issue by Yinteger** [HerpDerpinstine/bHapticsOSC#4]
Wish I could be more specific but I am not a unity expert.  I use an animation controller for Face Tracking set up with the Binary Face Tracking tool built by the VRChat face tracking community.  This animation controller works fine.  The controller the bHapticOSC plugin creates seems to modify the animation controller in a way that some of the face tracking breaks.  In my case specifically, my tongue gets stuck outside my mouth after I stick it out once.  Switching back to the non-bhaptic animation controller fixes the issue.  So the problem is definitely the bhaptic plugin modifying it in a way that seems to break some animations.

Let me know if there is any type of file I can attach to help you debug this.

**Comment by HerpDerpinstine** [comment]
Literally the only thing that bHapticsOSC does is make a copy of your currently set FX Layer then add parameters to it.
I keep seeing people say that its breaking animators but that should be quite impossible.
bHapticsOSC doesn't touch anything besides adding the needed parameters and linking them to the shader in a new layer if needed.
You can even verify this via the code that is used.

So I have absolutely no idea.
The only thing I can think of is that face tracking does something weird to the animator but that would be on the face tracking devs to fix.
Maybe see if they keep Write Defaults enabled or something.

**Comment by Yinteger** [comment]
Hey thanks for the reply.  I am asking in the Face Tracking community about it too.  But they do have Write Defaults enabled and disabling them breaks the face tracking animations.  They believe it is necessary for the face tracking to work using their tool and templates.  I am not entire sure how this would interact with the animations generated by bHapticOSC.  Should I update it to use Write Default too.  Apologies I am not entirely sure what write defaults does.

**Comment by HerpDerpinstine** [comment]
Can try and see.
I disable Write Defaults because the VRChat documentation recommends that you do so.
Maybe its breaking because some layers have it enabled while others don't.

**Comment by Yinteger** [comment]
Hey want to confirm this seemed to be the case.  Things are working fine now.

**Comment by HerpDerpinstine** [comment]
> Hey want to confirm this seemed to be the case. Things are working fine now.

What did you do?
Enable Write Defaults on the bHapticsOSC Layers?
