### ISSUE TITLE
The suit vibrates when I touch myself, but not when other people touch me

### ISSUE THREAD

**Issue by ledgend78** [HerpDerpinstine/bHapticsOSC#8]
I followed the directions, and the suit appears to be working, but only when I touch myself. I have personal bubble turned off, and it still doesn't work when other people touch me.

**Comment by HerpDerpinstine** [comment]
You need to change your VRChat Avatar Interaction settings.
![image](https://user-images.githubusercontent.com/8241943/180754836-dab2c9ce-8b83-4b02-9323-3919194c6fb0.png)
